server:
  port: 3002
eureka:
  serviceUrl:
    defaultZone: http://microservice-discovery:3002/eureka
  dashboard:
    path: /dashboard
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0