server:
  port: 3002
eureka:
  dashboard:
    path: /dashboard
  client:
    serviceUrl:
      defaultZone: http://msdiscovery:3002/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0